---
ip: "192.168.10.10"
memory: 1048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code
      type: "nfs"

sites:
    - map: homestead.app
      to: /home/vagrant/Code/Laravel/public
    - map: iball.app
      to: /home/vagrant/Code/iball/public
    - map: medd.io.app
      to: /home/vagrant/Code/medd.io/public
    - map: mydemo.app
      to: /home/vagrant/Code/mydemo/public

databases:
    - homestead

variables:
    - key: APP_ENV
      value: local

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar
